// ============================================
// Bridge module — public API entry point
// Re-exports all bridge types and constants from bridge-types.ts
// Consumers can import from "@open-agents/shared" (via index) or
// directly reference this module for tree-shaking clarity.
// ============================================

export {
  BRIDGE_PORT,
  BRIDGE_HOST,
  BRIDGE_BASE_URL,
  BRIDGE_WS_URL,
  BRIDGE_EXTENSION_ID,
} from "./bridge-types.js";

export type {
  BridgeHealthResponse,
  BridgeWorkspaceFolder,
  BridgeWorkspaceStateResponse,
  BridgeWindowStateResponse,
  BridgeCursorPosition,
  BridgeSelection,
  BridgeActiveEditorResponse,
  BridgeOpenFilesResponse,
  BridgeOpenFileRequest,
  BridgeOpenFileResponse,
  BridgeGetTextRequest,
  BridgeGetTextResponse,
  BridgeInsertTextRequest,
  BridgeReplaceTextRequest,
  BridgeSetCursorRequest,
  BridgeCloseEditorRequest,
  BridgeFileExistsResponse,
  BridgeReadFileRequest,
  BridgeReadFileResponse,
  BridgeWriteFileRequest,
  BridgeDeleteFileRequest,
  BridgeRenameFileRequest,
  BridgeCreateDirectoryRequest,
  BridgeListDirectoryRequest,
  BridgeListDirectoryResponse,
  BridgeTerminalInfo,
  BridgeListTerminalsResponse,
  BridgeCreateTerminalRequest,
  BridgeCreateTerminalResponse,
  BridgeSendTextRequest,
  BridgeKillTerminalRequest,
  BridgeExecuteCommandRequest,
  BridgeExecuteCommandResponse,
  BridgeExtensionInfo,
  BridgeListExtensionsResponse,
  BridgeDebugSession,
  BridgeDebugStateResponse,
  BridgeStartDebugRequest,
  BridgeScmChange,
  BridgeScmStateResponse,
  BridgeTaskDefinition,
  BridgeListTasksResponse,
  BridgeRunTaskRequest,
  BridgeEvent,
  BridgeAgentStatus,
  BridgeSpawnAgentRequest,
  BridgeSpawnAgentResponse,
  BridgeAgentInfo,
  BridgeAgentStatusResponse,
  BridgeAgentResultResponse,
  BridgeListAgentsResponse,
  BridgeErrorResponse,
} from "./bridge-types.js";
